spring.profiles.active: prod

server:
  port: 5000
#  servlet:
#    context-path: /resource-server

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://symbiocreation.auth0.com/
          audiences: rid6ZPjGfNTsGKlDGkQX97ECXJxLuzYa

spring.datasource.url: connection string # to be changed
spring.datasource.username: theusername # to be changed
spring.datasource.password: thepassword # to be changed
#spring.datasource.url: jdbc:mysql://localhost:3306/fablat_db
#spring.datasource.username: root
#spring.datasource.password: 01382155144

spring.jpa.show-sql: true
spring.jpa.properties.hibernate.format_sql: true
spring.jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.globally_quoted_identifiers: true

---
spring.config.activate.on-profile: dev
fablat.ui.uri: http://localhost:3000

logging:
  level:
    root: DEBUG
#    org.springframework.web: ERROR
#    org.springframework.security: DEBUG
#    com.auth0.example: TRACE


---
spring.config.activate.on-profile: prod
fablat.ui.uri: https://app.fab.lat
server:
  forward-headers-strategy: framework

logging:
  level:
    root: DEBUG
#    org.springframework.web: ERROR
#    org.springframework.security: DEBUG
#    com.auth0.example: TRACE



